language: c
before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - wget https://gist.github.com/C-Pro/8491912/raw/pg-pgtap-install.sh
  - sudo sh ./apt.postgresql.org.sh
  - cp install.cfg.example install.cfg
env:
  - PGVERSION=9.3
install:
  - bash pg-pgtap-install.sh
  - echo 'test' | bash ./install.sh
  - cat install.log
script:
  - cd test
  - pg_prove -h localhost -d skel_test -U postgres tests/run_*.sql