language: perl
services: postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install pgtap libtap-parser-sourcehandler-pgtap-perl
  - cp install.cfg.example install.cfg
install:
  - echo 'test' | bash ./install.sh
script:
  - cd test
  - bash ./run_tests.sh
