language: perl
services: postgresql
before_install:
  - wget http://api.pgxn.org/dist/pgtap/0.94.0/pgtap-0.94.0.zip
  - unzip pgtap-0.94.0.zip
  - cd pgtap-0.94.0
  - make
  - sudo make install
  - cd ..
  - cpanm TAP::Parser::SourceHandler::pgTAP
  - cp install.cfg.example install.cfg
install:
  - echo 'test' | bash ./install.sh
script:
  - cd test
  - bash ./run_tests.sh
