language: perl
services: postgresql
before_install:
  - cpanm TAP::Parser::SourceHandler::pgTAP
  - cp install.cfg.example install.cfg
install:
  - echo 'test' | bash ./install.sh
script:
  - cd test
  - bash ./run_tests.sh
