language: perl
services: postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install pgtap libtap-parser-sourcehandler-pgtap-perl
  - cp install.cfg.example install.cfg
install:
  - echo 'test' | bash ./install.sh
  - cat install.log
script:
  - cd test
  - pg_prove -h localhost -d skel_test -U postgres tests/run_*.sql