language: perl
services: postgresql
before_install:
  - sudo cpan TAP::Parser::SourceHandler::pgTAP
  - cp install.cfg.example install.cfg
install:
  - bash echo 'test' | ./install.sh
env:
  - PGVERSION=9.3
script:
  - cd test
  - bash ./run_tests.sh
